# Role
SQLSERVER_ROLE_ADMINISTRATOR    = 1
SQLSERVER_ROLE_CASHIER          = 2

# Status
SQLSERVER_STATUS_ACTIVE     = 1
SQLSERVER_STATUS_INACTIVE   = 2
SQLSERVER_STATUS_PAGADO     = 3
SQLSERVER_STATUS_NO_PAGADO  = 4
